describe("Modana HR Register Fail", function(){
	it("check wording indonesia", function(){

		cy.server()

		//scenario : checking wording in indonesia
        cy.visit("http://dev.modana.id/")
        cy.get('.row > :nth-child(2)')
            .click()
        cy.get('.el-form > .el-button')
            .click()
        cy.get(':nth-child(1) > .el-col > .el-form-item > .el-form-item__content > .el-form-item__error')
            .contains("Nomor Handphone dibutuhkan")
        cy.get(':nth-child(2) > :nth-child(1) > .el-form-item > .el-form-item__content > .el-form-item__error')
            .contains("Nama Depan dibutuhkan")
        cy.get(':nth-child(3) > :nth-child(2) > .el-form-item > .el-form-item__content > .el-form-item__error')
            .contains("Nama Perusahaan dibutuhkan")
        cy.get(':nth-child(4) > .el-col > .el-form-item > .el-form-item__content > .el-form-item__error')
            .contains("Jenis Perusahaan dibutuhkan")
        cy.get(':nth-child(5) > .el-col > .el-form-item > .el-form-item__content > .el-form-item__error')
            .contains("Jenis Industry dibutuhkan")
        cy.get(':nth-child(6) > :nth-child(1) > .el-form-item > .el-form-item__content > .el-form-item__error')
            .contains("Kata Sandi dibutuhkan")
        cy.get(':nth-child(6) > :nth-child(2) > .el-form-item > .el-form-item__content > .el-form-item__error')
            .contains("Konfirmasi Kata Sandi dibutuhkan")
    })
    it("phone number already registered", function(){

		cy.server()

		//scenario : if phone number already registered
		cy.route('POST', 'http://147.139.134.250:8081/v1/company').as('register')
		
        cy.visit("http://dev.modana.id/")
        cy.get('.row > :nth-child(2)')
            .click()
        cy.get('[style="width: 100%;"] > .mod-form-item > .el-input__inner')
            .type('807654323')
        cy.get(':nth-child(1) > .el-form-item > .el-form-item__content > .mod-form-item > .el-input__inner')
            .type('firstname')
        cy.get(':nth-child(2) > .el-form-item > .el-form-item__content > .mod-form-item > .el-input__inner')
            .type('middlename')
        cy.get(':nth-child(3) > .el-form-item > .el-form-item__content > .mod-form-item > .el-input__inner')
            .type('lastname')
        cy.get(':nth-child(3) > :nth-child(2) > .el-form-item > .el-form-item__content > .el-input > .el-input__inner')
            .type('PT Perusahaan')
        cy.get(':nth-child(4) > .el-col > .el-form-item > .el-form-item__content > .el-select > .el-input > .el-input__suffix > .el-input__suffix-inner > .el-select__caret')
            .click()
        cy.get('[style="min-width: 300.984px; position: absolute; top: 513px; left: 341px; transform-origin: center top; z-index: 2001;"] > .el-scrollbar > .el-select-dropdown__wrap > .el-scrollbar__view > :nth-child(1)')
            .click()
        cy.get(':nth-child(5) > .el-col > .el-form-item > .el-form-item__content > .el-select > .el-input > .el-input__suffix > .el-input__suffix-inner > .el-select__caret')
            .click()
        cy.get('[style="min-width: 300.984px; position: absolute; top: 259px; left: 341px; transform-origin: center bottom; z-index: 2004;"] > .el-scrollbar > .el-select-dropdown__wrap > .el-scrollbar__view > :nth-child(10)')
            .click()
        cy.get(':nth-child(6) > :nth-child(1) > .el-form-item > .el-form-item__content > .el-input > .el-input__inner')
            .type('12345678')
        cy.get(':nth-child(6) > :nth-child(2) > .el-form-item > .el-form-item__content > .el-input > .el-input__inner')
            .type('12345678')
        cy.get('.el-form > .el-button')
            .click()
        cy.get(':nth-child(1) > .el-col > .el-radio > .el-radio__input > .el-radio__inner')
            .click()
        cy.get(':nth-child(3) > :nth-child(1) > .el-button')
            .click()
        cy.wait('@register')
        cy.get('@register').then(function (xhr) {
            expect(400).to.eq(xhr.status)
            expect("Phone number already registered.").to.eq(xhr.response.body.err)
            expect(400).to.eq(xhr.body.status)
        })
        cy.wait(2*1500)
    })
})